package:
  exclude:
    - '**/*'
  include:
    - node_modules/**
    - utils/**
    - market-service/**

service: vinyl-search-market-service

functions:
  market-management-service:
      handler: market-service/market-main.main
      name:  ${self:service}-${opt:stage}
      environment:
        MONGODB_ATLAS_CLUSTER_URI: ${self:custom.env.MONGODB_ATLAS_CLUSTER_URI}
        BUCKET_NAME: ${self:custom.env.BUCKET_NAME}
        BUCKET_REGION: ${self:custom.env.BUCKET_REGION}
      events:
        - http:
            method: get
            path: /
            cors: true
        - http:
            method: get
            path: /{postId}
            cors: true
            authorizer:
              name: vinyl-authorizer
              arn:  ${self:custom.config.userpool_authorizer_arn}
        - http:
            method: get
            path: search
            cors: true
        - http:
            method: post
            path: /
            cors: true
            authorizer:
              name: vinyl-authorizer
              arn:  ${self:custom.config.userpool_authorizer_arn}


